---
- name: Upgrade the OS (apt-get upgrade)
  apt:
    upgrade: true
    update_cache: true
  when: apt_upgrade

- name: Install required packages
  apt:
    name: ['gnupg2', 'ca-certificates', 'software-properties-common', 'wget', 'curl', 'python3-pip', 'libpq-dev', 'acl', 'python3-yaml', 'python3-requests']
    state: present
    update_cache: true

- name: Add openstreetmap repository
  apt_repository:
    repo: ppa:osmadmins/ppa
    state: present
